template:
  files:
    main: file:template/main.hbs
    header: file:template/header.hbs
    footer: file:template/footer.hbs
  partials:
    infos: file:template/infos.hbs
  title: LINDAS - Linked Data Service

globals:
  datasetBaseUrl: env:DATASET_BASE_URL
  sparqlEndpoint:
    url: env:SPARQL_ENDPOINT_URL
    username: env:SPARQL_USERNAME
    password: env:SPARQL_PASSWORD

middlewares:
  morgan:
    module: trifid/middlewares/morgan.js
    order: 0

  static-assets:
    module: trifid-core/middlewares/static.js
    order: 0
    paths: /static-assets
    config:
      directory: file:static

  rewrite:
    module: trifid-core/middlewares/rewrite.js

  welcome:
    module: trifid-core/middlewares/view.js
    paths: /
    methods: GET
    config:
      path: views/welcome.hbs

  ecosystem:
    module: trifid-core/middlewares/view.js
    paths: /ecosystem/
    methods: GET
    config:
      path: views/ecosystem.hbs
  data-usage:
    module: trifid-core/middlewares/view.js
    paths: /data-usage/
    methods: GET
    config:
      path: views/data-usage.hbs
  governance:
    module: trifid-core/middlewares/view.js
    paths: /governance/
    methods: GET
    config:
      path: views/governance.hbs
  know-how:
    module: trifid-core/middlewares/view.js
    paths: /know-how/
    methods: GET
    config:
      path: views/know-how.hbs
  community:
    module: trifid-core/middlewares/view.js
    paths: /community/
    methods: GET
    config:
      path: views/community.hbs

  ckan:
    module: "@zazuko/trifid-plugin-ckan"
    order: 30
    paths: /ckan

  entity-renderer:
    module: "@zazuko/trifid-entity-renderer"
    config:
      path: views/entity.hbs
      labelLoader:
        #        labelNamespaces: # Labels will be fetched for URIs that start with this list (if omitted, fetches for all URIs)
        #          - https://lindas.admin.ch
        #          - https://ld.admin.ch
        chunkSize: 30
        concurrency: 2
        timeout: 4000

  yasgui:
    module: trifid-plugin-yasgui
    paths: /sparql
    config:
      urlShortener: https://s.zazuko.com/api/v1/shorten
      template: file:views/yasgui.hbs

  graph-explorer:
    module: trifid-plugin-graph-explorer
    paths: /graph-explorer
    config:
      dataLabelProperty: <http://schema.org/name> | rdfs:label
      schemaLabelProperty: <http://schema.org/name> | rdfs:label

  spex:
    module: trifid-plugin-spex
    paths: /spex

  search:
    module: file:plugins/search/index.js
    paths:
      - /datasets

  sparql-proxy:
    module: "@zazuko/trifid-plugin-sparql-proxy"
    paths: /query
    config:
      queryOperation: postQueryUrlencoded
      rewriteQueries: true
      cache:
        prefix: env:SPARQL_PROXY_CACHE_PREFIX
        url: env:SPARQL_PROXY_CACHE_URL
        clearAtStartup: env:SPARQL_PROXY_CACHE_CLEAR_AT_STARTUP

  handle-redirects-demo:
    module: "@zazuko/trifid-handle-redirects"

  sparql-handler:
    module: trifid-handler-sparql
    config:
      resourceExistsQuery: "ASK { GRAPH ?g { <${iri}> ?p ?o }}"
      resourceGraphQuery: "#pragma describe.strategy cbd\nDESCRIBE <${iri}>"
      containerExistsQuery: "ASK { GRAPH ?g { <${iri}> ?p ?o }}"
      containerGraphQuery: "#pragma describe.strategy cbd\nDESCRIBE <${iri}>"

  i18n:
    module: trifid-plugin-i18n
    order: 5
    config:
      directory: file:locales
      locales:
        - en
        - fr
        - de
        - it

  menu:
    module: file:plugins/menu/index.js
    order: 80
    config:
      namespace: header
      entries:
        - path: /datasets/
          label: Data Catalog
        - path: /sparql/
          label: Query Data
        - path: /ecosystem/
          label: Ecosystem
        - path: /data-usage/
          label: Data Usage
        - path: /governance/
          label: Governance
        - path: /know-how/
          label: Know How
        - path: /community/
          label: Community

  content:
    module: "@zazuko/trifid-markdown-content"
    order: 80
    config:
      defaults:
        autoLink: true # create links from headings
        idPrefix: "content-" # prefix for generated ids for headings
        classes: # custom CSS classes for generated HTML elements
          h1: h1
          h2: h2
          h3: h3
          h4: h4
          h5: h5
          table: table

      entries:
        lindas:
          directory: file:content/template-parts
          # entries used in templates using `{{{ locals.markdown-content-plugin.lindas.XXXXXXXX }}}`

        lindas-root:
          directory: file:content/root-pages
          mountPath: /

        lindas-ecosystem:
          directory: file:content/ecosystem
          mountPath: /ecosystem/

        lindas-data-usage:
          directory: file:content/data-usage
          mountPath: /data-usage/

        lindas-governance:
          directory: file:content/governance
          mountPath: /governance/

        lindas-know-how:
          directory: file:content/know-how
          mountPath: /know-how/

        lindas-community:
          directory: file:content/community
          mountPath: /community/
