template:
  files:
    main: file:template/main.hbs
    header: file:template/header.hbs
    footer: file:template/footer.hbs
  partials:
    infos: file:template/infos.hbs
  title: LINDAS - Linked Data Service

globals:
  datasetBaseUrl: env:DATASET_BASE_URL
  endpoints:
    default:
      url: /query

plugins:
  health-old:
    module: trifid-core/plugins/health.js
    paths: /health

  i18n:
    module: trifid-plugin-i18n
    config:
      directory: file:locales
      updateFiles: false
      locales:
        - en
        - fr
        - de
        - it

  static-assets:
    module: trifid-core/plugins/static.js
    paths: /static-assets
    config:
      directory: file:static

  welcome:
    module: trifid-core/plugins/view.js
    paths: /
    config:
      path: views/welcome.hbs

  ecosystem:
    module: trifid-core/plugins/view.js
    paths: /ecosystem/
    config:
      path: views/ecosystem.hbs
  data-usage:
    module: trifid-core/plugins/view.js
    paths: /data-usage/
    config:
      path: views/data-usage.hbs
  governance:
    module: trifid-core/plugins/view.js
    paths: /governance/
    config:
      path: views/governance.hbs
  know-how:
    module: trifid-core/plugins/view.js
    paths: /know-how/
    config:
      path: views/know-how.hbs
  community:
    module: trifid-core/plugins/view.js
    paths: /community/
    config:
      path: views/community.hbs

  ckan:
    module: "@zazuko/trifid-plugin-ckan"
    paths:
      - /ckan
      - /ckan/

  yasgui:
    module: trifid-plugin-yasgui
    config:
      urlShortener: https://s.zazuko.com/api/v1/shorten
      template: file:views/yasgui.hbs

  graph-explorer:
    module: trifid-plugin-graph-explorer
    config:
      dataLabelProperty: <http://schema.org/name> | rdfs:label
      schemaLabelProperty: <http://schema.org/name> | rdfs:label
      template: file:views/graph-explorer.hbs

  spex:
    module: trifid-plugin-spex

  search:
    module: file:plugins/search/index.js

  sparql-proxy:
    module: "@zazuko/trifid-plugin-sparql-proxy"
    paths: /query
    config:
      allowRewriteToggle: true
      rewrite: false
      rewriteQuery: true
      rewriteResults: true
      endpointUrl: env:SPARQL_ENDPOINT_URL
      username: env:SPARQL_ENDPOINT_USERNAME
      password: env:SPARQL_ENDPOINT_PASSWORD

  menu:
    module: file:plugins/menu/index.js
    config:
      namespace: header
      entries:
        - path: /datasets/
          label: Data Catalog
        - path: /sparql/
          label: Query Data
        - path: /ecosystem/
          label: Ecosystem
        - path: /data-usage/
          label: Data Usage
        - path: /governance/
          label: Governance
        - path: /know-how/
          label: Know How
        - path: /community/
          label: Community

  content:
    module: "@zazuko/trifid-markdown-content"
    config:
      defaults:
        autoLink: true # create links from headings
        idPrefix: "content-" # prefix for generated ids for headings
        classes: # custom CSS classes for generated HTML elements
          h1: h1
          h2: h2
          h3: h3
          h4: h4
          h5: h5
          table: table
        template: file:views/content.hbs

      entries:
        lindas:
          directory: file:content/template-parts
          # entries used in templates using `{{{ locals.markdown-content-plugin.lindas.XXXXXXXX }}}`

        lindas-root:
          directory: file:content/root-pages
          mountPath: /

        lindas-ecosystem:
          directory: file:content/ecosystem
          mountPath: /ecosystem/

        lindas-data-usage:
          directory: file:content/data-usage
          mountPath: /data-usage/

        lindas-governance:
          directory: file:content/governance
          mountPath: /governance/

        lindas-know-how:
          directory: file:content/know-how
          mountPath: /know-how/

        lindas-community:
          directory: file:content/community
          mountPath: /community/

  entity-renderer:
    module: "@zazuko/trifid-entity-renderer"
    config:
      path: views/entity.hbs
      labelLoader:
        #        labelNamespaces: # Labels will be fetched for URIs that start with this list (if omitted, fetches for all URIs)
        #          - https://lindas.admin.ch
        #          - https://ld.admin.ch
        chunkSize: 30
        concurrency: 2
        timeout: 4000
      rewrite: true

      # Custom queries to get information about a resource or container
      resourceExistsQuery: "ASK { GRAPH ?g { <{{iri}}> ?p ?o }}"
      resourceGraphQuery: "#pragma describe.strategy cbd\nDESCRIBE <{{iri}}>"
      containerExistsQuery: "ASK { GRAPH ?g { <{{iri}}> ?p ?o }}"
      containerGraphQuery: "#pragma describe.strategy cbd\nDESCRIBE <{{iri}}>"
