# yaml-language-server: $schema=https://unpkg.com/trifid-core@latest/lib/config/schema.json

extends:
  - config.yaml

globals:
  datasetBaseUrl: ""

plugins:
  sparql-proxy:
    module: "@zazuko/trifid-plugin-sparql-proxy"
    paths: /x-query
    config:
      # BEGIN: disable rewrites
      allowRewriteToggle: false
      rewrite: false
      rewriteQuery: false
      rewriteResults: false
      # END: disable rewrites
      endpoints:
        default:
          url: https://lindas.admin.ch/query
          username: env:SPARQL_ENDPOINT_USERNAME
          password: env:SPARQL_ENDPOINT_PASSWORD
        int:
          url: https://int.lindas.admin.ch/query
        test:
          url: https://test.lindas.admin.ch/query
      endpointUrl: https://ld.admin.ch/query
      username: env:SPARQL_ENDPOINT_USERNAME
      password: env:SPARQL_ENDPOINT_PASSWORD
      formats:
        ttl: "text/turtle"
        nt: "application/n-triples"
        xml: "application/rdf+xml"
        jsonld: "application/ld+json"
        csv: "text/csv"
      queryLogLevel: info

  entity-renderer:
    module: "@zazuko/trifid-entity-renderer"
    config:
      path: views/entity.hbs
      labelLoader:
        chunkSize: 30
        concurrency: 2
        timeout: 4000
      followRedirects: true
      enableSchemaUrlRedirect: true
      allowEndpointSwitch: true

      # BEGIN: disable rewrites
      rewrite: false
      # END: disable rewrites

      # Custom queries to get information about a resource or container
      resourceExistsQuery: "ASK { GRAPH ?g { <{{iri}}> ?p ?o }}"
      resourceGraphQuery: "#pragma describe.strategy cbd\nDESCRIBE <{{iri}}>"
      containerExistsQuery: "ASK { GRAPH ?g { <{{iri}}> ?p ?o }}"
      containerGraphQuery: "#pragma describe.strategy cbd\nDESCRIBE <{{iri}}>"
